name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runs-on: ubuntu-latest
  prepare:
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1
    - name: Generate build system
      run: mkdir build && cd build && cmake ..
  build:
    steps:
    - name: Build
      run: cd build && make release
  export artifacts:
    steps:    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: testMain
        path: out/bin/release/testMain
    