name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.1.1
    - name: Generate build system
      run: mkdir build && cd build && cmake ..
    - name: Build
      run: cd build && make release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: testMain
        path: out/bin/release/testMain
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Generate build system
      run: rm PreLoad.cmake && mkdir build && cd build && cmake ..
    - name: Build
      run: cd build && MSBuild pcConMon.sln /p:Configuration=Release /p:Platform=x64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: testMain.exe
        path: out/bin/release/testMain.exe
